name       : kicad-packages3d
version    : 7.0.6
release    : 5
source     :
    - https://gitlab.com/kicad/libraries/kicad-packages3D/-/archive/7.0.6/kicad-packages3D-7.0.6.tar.gz : 8c3f295e746300f5f430c251b8c797b3e171ed5f10088e33e7476613ffed23e3
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad 3D model libraries for rendering and MCAD integration
description: |
    Contains 3D models for rendering and MCAD integration, for use with KiCAD EDA software. The model needs a mechanical model source (a manually-modelled or script-generated file); its WRL counterpart file must be obtained as a conversion from the MCAD model.
setup      : |
    %cmake
install    : |
    %make_install
