name       : kicad-packages3d
version    : 5.1.6
release    : 3
source     :
    - https://github.com/KiCad/kicad-packages3D/archive/5.1.6.tar.gz : c455712a9eacdbbabf3367977911152f2e616bf8f622962f0fd4f3c6ddd00038
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad 3D model libraries for rendering and MCAD integration
description: |
    Contains 3D models for rendering and MCAD integration, for use with KiCAD EDA software. The model needs a mechanical model source (a manually-modelled or script-generated file); its WRL counterpart file must be obtained as a conversion from the MCAD model.
setup      : |
    %cmake
install    : |
    %make_install
