name       : kicad-packages3d
version    : 5.0.0
release    : 1
source     :
    - https://github.com/KiCad/kicad-packages3D/archive/5.0.0.tar.gz : 8e9b0dfb886e1ec699474b2438c0e92b2a2148950d015c6af4f85c38ca20d659
license    : CC-BY-SA-4.0
component  : office
summary    : Official KiCad 3D model libraries for rendering and MCAD integration
description: |
    Contains 3D models for rendering and MCAD integration, for use with KiCAD EDA software. The model needs a mechanical model source (a manually-modelled or script-generated file); its WRL counterpart file must be obtained as a conversion from the MCAD model.
setup      : |
    %cmake
install    : |
    %make_install
