name       : kicad-packages3d
version    : 5.1.12
release    : 4
source     :
    - https://gitlab.com/kicad/libraries/kicad-packages3D/-/archive/5.1.12/kicad-packages3D-5.1.12.tar.bz2 : cf776c1cc76f9c0f2901111bf34350fcc5ddab20e658f07d150b81306107662e
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad 3D model libraries for rendering and MCAD integration
description: |
    Contains 3D models for rendering and MCAD integration, for use with KiCAD EDA software. The model needs a mechanical model source (a manually-modelled or script-generated file); its WRL counterpart file must be obtained as a conversion from the MCAD model.
setup      : |
    %cmake
install    : |
    %make_install
